### ISSUE TITLE
申请权限时出现闪退，FragmentManager被占用

### ISSUE THREAD

**Issue by MoonBlueSky** [soulqw/SoulPermission#20]
在Fragment中网络请求时，调用申请设备标识时遇到FragmentManager被占用从而闪退，希望大佬能帮忙解决一下
错误信息：
2019-06-21 14:32:39.432 18707-18707/com.myworld.p.account E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myworld.p.account, PID: 18707
    java.lang.IllegalStateException: FragmentManager is already executing transactions
        at androidx.fragment.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:2207)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2267)
        at androidx.fragment.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:814)
        at com.qw.soul.permission.request.PermissionFragmentFactory.create(PermissionFragmentFactory.java:27)
        at com.qw.soul.permission.request.PermissionRequester.<init>(PermissionRequester.java:27)
        at com.qw.soul.permission.SoulPermission.requestRuntimePermission(SoulPermission.java:364)
        at com.qw.soul.permission.SoulPermission.access$000(SoulPermission.java:33)
        at com.qw.soul.permission.SoulPermission$3.onStatusOk(SoulPermission.java:352)
        at com.qw.soul.permission.SoulPermission.checkStatusBeforeDoSomething(SoulPermission.java:345)
        at com.qw.soul.permission.SoulPermission.requestPermissions(SoulPermission.java:349)
        at com.qw.soul.permission.SoulPermission.checkAndRequestPermissions(SoulPermission.java:174)
        at com.qw.soul.permission.SoulPermission.checkAndRequestPermission(SoulPermission.java:140)
        at com.myworld.lib.code.utils.SystemUtils.getDeviceId(SystemUtils.java:114)

**Comment by soulqw** [comment]
刚刚看了下，你这边应该是1.1.7的版本，升级到最新到1.1.8已经解决此问题
[https://github.com/soulqw/SoulPermission/releases](url)
@MoonBlueSky
