### ISSUE TITLE
1.3.1版本 FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by wangchenyan** [soulqw/SoulPermission#39]
Fatal Exception: java.lang.IllegalStateException: FragmentManager is already executing transactions
       at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1686)
       at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1716)
       at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
       at com.qw.soul.permission.request.PermissionFragmentFactory.create(PermissionFragmentFactory.java:35)
       at com.qw.soul.permission.request.PermissionRequester.<init>(PermissionRequester.java:29)
       at com.qw.soul.permission.SoulPermission.requestRuntimePermission(SoulPermission.java:405)
       at com.qw.soul.permission.SoulPermission.access$000(SoulPermission.java:41)
       at com.qw.soul.permission.SoulPermission$4.onStatusOk(SoulPermission.java:398)
       at com.qw.soul.permission.SoulPermission.checkStatusBeforeDoSomething(SoulPermission.java:391)
       at com.qw.soul.permission.SoulPermission.requestPermissions(SoulPermission.java:395)
       at com.qw.soul.permission.SoulPermission.checkAndRequestPermissions(SoulPermission.java:208)
       at common.permission.Permissioner.requestPermissions(Permissioner.kt:36)
       at common.permission.Permissioner.requestStoragePermission(Permissioner.kt:57)
       at com.*.requestPermission(*.kt:79)
       at com.*.onLazyCreate(*.kt:55)
       at com.*.lazyCreate(LazyFragment.kt:58)
       at com.*.onResume(LazyFragment.kt:48)
       at com.*.onResume(BaseFragment.kt:13)
       at androidx.fragment.app.Fragment.performResume(Fragment.java:3180)
       at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:606)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1808)
       at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1720)
       at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:317)
       at androidx.viewpager2.adapter.FragmentStateAdapter$FragmentMaxLifecycleEnforcer.updateFragmentMaxLifecycle(FragmentStateAdapter.java:726)
       at androidx.viewpager2.adapter.FragmentStateAdapter$FragmentMaxLifecycleEnforcer$1.onPageScrollStateChanged(FragmentStateAdapter.java:632)
       at androidx.viewpager2.widget.CompositeOnPageChangeCallback.onPageScrollStateChanged(CompositeOnPageChangeCallback.java:87)
       at androidx.viewpager2.widget.CompositeOnPageChangeCallback.onPageScrollStateChanged(CompositeOnPageChangeCallback.java:87)
       at androidx.viewpager2.widget.ScrollEventAdapter.dispatchStateChanged(ScrollEventAdapter.java:426)
       at androidx.viewpager2.widget.ScrollEventAdapter.onScrolled(ScrollEventAdapter.java:214)
       at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5347)
       at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5512)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1034)
       at android.view.Choreographer.doCallbacks(Choreographer.java:858)
       at android.view.Choreographer.doFrame(Choreographer.java:785)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1019)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:7912)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by soulqw** [comment]
@wangchenyan  把权限请求时机修改到非Fragment创建时候试试，比如做个延时
